/// <reference types="cypress" />

// AI-generated by QAFLOW Test Cover Engine.
// URL:      http://localhost:3001/index.html
// Mode:     black-box
// Focus:    smoke, navigation

describe("AI smoke — SportHub — Gear Up For Greatness", () => {
  beforeEach(() => cy.visit("/index.html"));

  it("page renders the expected document title", () => {
    cy.title().should("include", 'SportHub — Gear Up For Greatness');
  });

  it("renders heading: 'SPORTHUB'", () => {
    cy.get('h1').should("contain.text", 'SPORTHUB');
  });

  it("renders heading: 'Gear up for greatnes.'", () => {
    cy.get('h2').should("contain.text", 'Gear up for greatnes.');
  });

  it("renders heading: 'Hot Picks'", () => {
    cy.get('h3').should("contain.text", 'Hot Picks');
  });

  it("renders heading: 'Velocity Pro Runner'", () => {
    cy.get('h4').should("contain.text", 'Velocity Pro Runner');
  });

  it("renders heading: 'Air Strike Basketball'", () => {
    cy.get('h4').should("contain.text", 'Air Strike Basketball');
  });

  it("button 'Search' is visible and labelled", () => {
    cy.get('#search-btn').should("be.visible").and("contain.text", 'Search');
  });

  it("link 'Home' points to /index.html", () => {
    cy.get('a[href="/index.html"]').should("have.attr", "href", "/index.html");
  });

  it("link 'Products' points to /products.html", () => {
    cy.get('a[href="/products.html"]').should("have.attr", "href", "/products.html");
  });

  it("link 'Cart' points to /cart.html", () => {
    cy.get('a[href="/cart.html"]').should("have.attr", "href", "/cart.html");
  });

  it("link 'Sign In' points to /login.html", () => {
    cy.get('a[href="/login.html"]').should("have.attr", "href", "/login.html");
  });

  it("link '👟\nRunning' points to /products.html?cat=Running", () => {
    cy.get('a[href="/products.html?cat=Running"]').should("have.attr", "href", "/products.html?cat=Running");
  });

});
