# AI-generated by QAFLOW Test Cover Engine.
# URL: http://localhost:3001/login.html

import pytest
from playwright.sync_api import Page, expect

BASE_URL = 'http://localhost:3001/login.html'


@pytest.fixture(autouse=True)
def _open_page(page: Page):
    page.goto(BASE_URL)
    yield


def test_page_title(page: Page):
    expect(page).to_have_title('Login · SportHub')

def test_button_login_button_visible(page: Page):
    expect(page.locator('#login-button')).to_be_visible()

def test_form_login_form_inputs(page: Page):
    expect(page.locator('#email')).to_be_visible()
    expect(page.locator('#password')).to_be_visible()

