// Page object generated by QAFLOW Test Cover Engine.
// Source URL: http://localhost:3001/login.html
//
// Encapsulates every locator + high-level action for the page so spec
// files stay declarative. Add domain actions (e.g. `loginAs`) on top of
// the locators below as your suite grows.

export class LoginSporthub {
  visit() { cy.visit(this.url()); }

  url() { return 'http://localhost:3001/login.html'; }
  pageTitle() { return cy.title(); }
  sporthubHeading() { return cy.get('h1'); }
  sign_in_to_your_accountHeading() { return cy.get('h2'); }
  loginButton() { return cy.get('#login-button'); }
  emailInput() { return cy.get('#email'); }
  passwordInput() { return cy.get('#password'); }
  homeLink() { return cy.get("a[href='/index.html']"); }
  productsLink() { return cy.get("a[href='/products.html']"); }
  cartLink() { return cy.get("a[href='/cart.html']"); }
  loginLink() { return cy.get("a[href='/login.html']"); }
}
