/// <reference types="cypress" />

// AI-generated by QAFLOW Test Cover Engine.
// URL:      http://localhost:3001/login.html
// Mode:     black-box
// Focus:    smoke

describe("AI smoke — Login · SportHub", () => {
  beforeEach(() => cy.visit("/login.html"));

  it("page renders the expected document title", () => {
    cy.title().should("include", 'Login · SportHub');
  });

  it("renders heading: 'SPORTHUB'", () => {
    cy.get('h1').should("contain.text", 'SPORTHUB');
  });

  it("renders heading: 'Sign in to your account'", () => {
    cy.get('h2').should("contain.text", 'Sign in to your account');
  });

  it("button 'Login' is visible and labelled", () => {
    cy.get('#login-button').should("be.visible").and("contain.text", 'Login');
  });

  it("link 'Home' points to /index.html", () => {
    cy.get('a[href="/index.html"]').should("have.attr", "href", "/index.html");
  });

  it("link 'Products' points to /products.html", () => {
    cy.get('a[href="/products.html"]').should("have.attr", "href", "/products.html");
  });

  it("link 'Cart' points to /cart.html", () => {
    cy.get('a[href="/cart.html"]').should("have.attr", "href", "/cart.html");
  });

  it("link 'Login' points to /login.html", () => {
    cy.get('a[href="/login.html"]').should("have.attr", "href", "/login.html");
  });

  it("form login-form has its expected inputs", () => {
    cy.get('#email').should("exist");
    cy.get('#password').should("exist");
  });

});
